# Generated by Django 5.0.4 on 2024-04-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('descriptionid', models.AutoField(primary_key=True, serialize=False)),
                ('descriptiontexte', models.TextField()),
                ('Ingredients', models.TextField()),
                ('Flavors', models.TextField()),
                ('Recommendedusage', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('description_id', models.IntegerField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite', models.IntegerField()),
                ('image', models.ImageField(upload_to='produits/')),
                ('categorie_id', models.IntegerField()),
                ('size', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('effects', models.CharField(max_length=255)),
                ('tags', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=255)),
                ('reviews_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reviewstexte', models.TextField()),
                ('reviewsnumber', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
    ]
