# Generated by Django 5.0.4 on 2024-04-27 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.user')),
                ('role', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            bases=('myapp.user',),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.user')),
                ('address', models.TextField()),
                ('tel', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('account_creation_date', models.DateField()),
                ('role', models.CharField(max_length=255)),
            ],
            bases=('myapp.user',),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.user')),
                ('department', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            bases=('myapp.user',),
        ),
    ]
