# Generated by Django 5.0.4 on 2024-04-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_admin_client_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='password',
            new_name='department',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='role',
        ),
        migrations.RemoveField(
            model_name='client',
            name='password',
        ),
        migrations.RemoveField(
            model_name='client',
            name='role',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='password',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=5, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
