# Generated by Django 5.0.4 on 2024-06-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_author_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_2',
            field=models.TextField(default='Default content'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_3',
            field=models.TextField(default='Default content'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_4',
            field=models.TextField(default='Default content'),
        ),
        migrations.AddField(
            model_name='post',
            name='des',
            field=models.TextField(default='Default description'),
        ),
        migrations.AddField(
            model_name='post',
            name='p1',
            field=models.TextField(default='Default paragraph 1'),
        ),
        migrations.AddField(
            model_name='post',
            name='p2',
            field=models.TextField(default='Default paragraph 2'),
        ),
        migrations.AddField(
            model_name='post',
            name='p3',
            field=models.TextField(default='Default paragraph 3'),
        ),
        migrations.AddField(
            model_name='post',
            name='p4',
            field=models.TextField(default='Default paragraph 4'),
        ),
        migrations.AddField(
            model_name='post',
            name='quotes',
            field=models.TextField(default='Default content'),
        ),
        migrations.AddField(
            model_name='post',
            name='quotes_author',
            field=models.TextField(default='Default content'),
        ),
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='title1',
            field=models.TextField(default='Default title1'),
        ),
        migrations.AddField(
            model_name='post',
            name='title2',
            field=models.TextField(default='Default title2'),
        ),
        migrations.AddField(
            model_name='post',
            name='title3',
            field=models.TextField(default='Default title3'),
        ),
    ]
