# Generated by Django 5.0.4 on 2024-06-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_post_content_2_post_content_3_post_content_4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_4',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='des',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='p1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='p2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='p3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='p4',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='quotes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='quotes_author',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='title1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='title2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='title3',
            field=models.TextField(),
        ),
    ]
