# Generated by Django 5.0.4 on 2024-06-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_post_content_2_alter_post_content_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_5',
            field=models.TextField(default='Default text 5'),
        ),
        migrations.AddField(
            model_name='post',
            name='desimage',
            field=models.TextField(default='Default text'),
        ),
        migrations.AddField(
            model_name='post',
            name='pp1',
            field=models.TextField(default='Default text'),
        ),
        migrations.AddField(
            model_name='post',
            name='pp2',
            field=models.TextField(default='Default text'),
        ),
        migrations.AddField(
            model_name='post',
            name='pp3',
            field=models.TextField(default='Default text'),
        ),
        migrations.AddField(
            model_name='post',
            name='pp4',
            field=models.TextField(default='Default text'),
        ),
    ]
